FRIEND_REQUEST = "fr"
REQUEST_ACCEPTED = "ra"
REQUEST_REJECTED = "rj"
NEW_PICTURE_ADDED = "npa"
PROJECT_FOLLOWING_UPDATE = "pfu"
NEW_TASK_FEED = "ntf"
NEW_PICTURE_FEED = "npf"
NEW_PROFILE_PICTURE_FEED = "nppf"
CORRECT_VOUCH = 'cv'
MISSED_VOUCH_OPPURTUNITY = 'mvo'
FAILED_TASKS = 'ft'
COMPLETED_TASKS = 'ct'
INCORRECT_VOUCH = 'iv'
BEFORE_PICTURE = 'bc'
AFTER_PICTURE = 'ac'
MILESTONE = 'mt'
PICTURE_SET = 'ps'
NEW_PROJECT = 'np'
PERSON_SEARCH = 'psr'
PROJECT_TAG_SEARCH = 'pisr'
PROJECT_NAME_SEARCH = 'pisr'
MILESTONE_NAME_SEARCH = 'mns'
ADD_TO_POND = 'atp'
POND_REQUEST = 'prq'


